name: Generate GitHub Stats Cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: GitHub Stats Card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: profile/github-stats.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Karachi

      - name: Languages Card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: profile/languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

      - name: Achievements Card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: profile/achievements.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
